In [1]:
import numpy as np

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) 
# Inputs to Neural Network
y = np.array(([92], [86], [89]), dtype=float)
#Actual output of Neural Network

In [3]:
X #(9,5,6)

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [4]:
y

array([[92.],
       [86.],
       [89.]])

In [5]:
X = X/np.amax(X,axis=0)
y = y/100

In [6]:
X

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [7]:
y

array([[0.92],
       [0.86],
       [0.89]])

In [8]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [9]:
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [10]:
#Variable initialization
epoch=7000 #Setting training iterations
lr=0.1 #Setting learning rate

In [11]:
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer


In [12]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
print("current wout is")
print(wout)
bout=np.random.uniform(size=(1,output_neurons))

current wout is
[[0.19151177]
 [0.22383187]
 [0.37028328]]


In [13]:
for i in range(epoch):
#Forward Propogation
    h_ip=np.dot(X,wh) + bh
    h_act = sigmoid(h_ip)
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)
    #Backpropagation
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    # Error at Hidden Layer
    Eh = d_output.dot(wout.T)
    #print("wout is\n",i)
    #print(wout.T)
    hiddengrad = derivatives_sigmoid(h_act)
    d_hidden = Eh * hiddengrad
    wout += h_act.T.dot(d_output) *lr
    wh += X.T.dot(d_hidden) *lr

In [14]:
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Learned Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Learned Output: 
 [[0.89484632]
 [0.87779012]
 [0.89699592]]
