In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix


In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
iris=datasets.load_iris()

In [5]:
iris_data=iris.data

In [6]:
iris_labels=iris.target

In [7]:
#print(iris_data)

In [8]:
#print(iris_labels)

In [9]:
x_train,x_test,y_train,y_test=train_test_split(iris_data,iris_labels,test_size=0.40)

In [10]:
len(x_train)

90

In [11]:
len(x_test)

60

In [12]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [13]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [14]:
y_pred=classifier.predict(x_test)

In [15]:
print('Confusion Matrix is as follows')
print(confusion_matrix(y_test,y_pred))

Confusion Matrix is as follows
[[22  0  0]
 [ 0 16  1]
 [ 0  2 19]]


In [16]:
print('Accuracy Metrics')
print(classification_report(y_test,y_pred))

Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.89      0.94      0.91        17
           2       0.95      0.90      0.93        21

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60

